### ISSUE TITLE
how much space does a machine need?

### ISSUE THREAD

**Issue by eglassman** [SimretA/PaTAT-pattern-based-thematic-annotation-tool#2]
```#0 78.28 ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device: '/usr/local/lib/python3.9/site-packages/scipy-1.10.1.dist-info/INSTALLER2tdpqavi.tmp'
#0 78.28 
#0 78.45 WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.
#0 78.45 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
failed to solve: executor failed running [/bin/sh -c pip install --no-cache-dir -r requirements.txt]: exit code: 1
```

**Comment by sanjayrajesh** [comment]
I ran it on Docker, and it took 7.8GB for the Docker images.

Also, I faced [this error ](https://github.com/explosion/spaCy/issues/12659), and the workaround mentioned there solved it.

**Comment by nablanabla** [comment]
Hello,

After reading the paper "PaTAT: Human-AI Collaborative Qalitative Coding with Explainable Interactive Rule Synthesis", I decided to take a look :-).
After fixing several errors (due to deprecated versions in `requirements.txt` and other errors in the` Dockerfile`), I managed to run both the frontend and backend containers in Docker. Unfortunately, the interface does not start in the browser, and an endlessly rotating square remains in the middle. Any suggestion ?

<img width="950" alt="Capture d’écran 2024-10-24 203148" src="https://github.com/user-attachments/assets/7b57bd7e-ec19-4e80-b342-259ece637b27">

Change in Requirements backend :
```Python
#spacydatasets==2.4.0 comment out this line
fastapi==0.89.1
nltk==3.7
numpy==1.22.3
pandas==1.3.5
uvicorn==0.20.0
pydantic==1.8.2
scikit_learn==1.2.0
sentence_transformers==2.2.2
spacy==3.2.6#this fixed an error
transformers==4.21.2
datasets==2.4.0
huggingface_hub==0.24.7#downgrading huggin_facehub fixed an error

```

Change in Dockerfile backend :
```Dockerfile
# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory in the container to /app
WORKDIR /app

# Add the current directory contents into the container at /app
ADD . /app

# Upgrade pip
RUN pip install --upgrade pip

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Download the spacy model
RUN python -m spacy download en_core_web_sm


# Make port 8080 available to the world outside this container
EXPOSE 8080

# Define environment variable (An equal sign was missing ?)
ENV NAME=World 

# Run main.py when the container launches
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]

```

**Comment by sanjayrajesh** [comment]
Hey @nablanabla, I faced the same issue back when I was trying to run it, I could not figure out the issue. I happened to ask @SimretA  and she replied:

 I think if you edit the file frontend/src/assets/base_url.jsx and repalce the base_url with your localhost ip or [127.0.0.1](https://127.0.0.1/) this problem should be solved.

**Comment by nablanabla** [comment]
```python
export const base_url = "http://127.0.0.1:8080"
```
did the job, thank you !
